<?xml version="1.0" encoding="utf-8"?><Database Name="agent" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DAVID-7;Initial Catalog=agent;Integrated Security=True" SettingsObjectName="SIP_Agent.Properties.Settings" SettingsPropertyName="agentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tasks" Member="tasks">
    <Type Name="task">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="details" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="notifier_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="person_task" Member="person" ThisKey="notifier_id" OtherKey="id" Type="person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.persons" Member="persons">
    <Type Name="person">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Member="password" Type="System.String" CanBeNull="false" />
      <Association Name="person_task" Member="tasks" ThisKey="id" OtherKey="notifier_id" Type="task" />
    </Type>
  </Table>
</Database>