<?xml version="1.0" encoding="utf-8"?><Database Name="sip-agent" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TÕNIS-PC\SIPAGENT;Initial Catalog=sip-agent;Integrated Security=True" SettingsObjectName="SIP_Agent.Properties.Settings" SettingsPropertyName="sip_agentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.calls" Member="calls">
    <Type Name="call">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="summary" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="caller_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="clerk_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="received" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="finished" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="call_tasks_call" Member="tasks_calls" ThisKey="id" OtherKey="call_id" Type="tasks_call" />
      <Association Name="person_call" Member="person" ThisKey="clerk_id" OtherKey="id" Type="person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.companies" Member="companies">
    <Type Name="company">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="company_person" Member="persons" ThisKey="id" OtherKey="company_id" Type="person" />
    </Type>
  </Table>
  <Table Name="dbo.logs" Member="logs">
    <Type Name="log">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="person_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="person_log" Member="person" ThisKey="person_id" OtherKey="id" Type="person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.persons" Member="persons">
    <Type Name="person">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="NChar(64)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="NChar(64)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NChar(32)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(32)" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="person_call" Member="calls" ThisKey="id" OtherKey="clerk_id" Type="call" />
      <Association Name="person_log" Member="logs" ThisKey="id" OtherKey="person_id" Type="log" />
      <Association Name="person_task" Member="tasks" ThisKey="id" OtherKey="assignee_id" Type="task" />
      <Association Name="person_task1" Member="tasks1" ThisKey="id" OtherKey="clerk_id" Type="task" />
      <Association Name="company_person" Member="company" ThisKey="company_id" OtherKey="id" Type="company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.phonebook" Member="phonebooks">
    <Type Name="phonebook">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(40)" CanBeNull="true" />
      <Column Name="person_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.task_categories" Member="task_categories">
    <Type Name="task_category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="task_category_task_category" Member="task_categories" ThisKey="id" OtherKey="parent_id" Type="task_category" />
      <Association Name="task_category_task" Member="tasks" ThisKey="id" OtherKey="category_id" Type="task" />
      <Association Name="task_category_task_category" Member="task_category1" ThisKey="parent_id" OtherKey="id" Type="task_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.task_statuses" Member="task_statuses">
    <Type Name="task_statuses">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="task_statuse_task_statuse" Member="task_statuses1" ThisKey="id" OtherKey="parent_id" Type="task_statuses" />
      <Association Name="task_statuse_task" Member="tasks" ThisKey="id" OtherKey="status_id" Type="task" />
      <Association Name="task_statuse_task_statuse" Member="task_statuse1" ThisKey="parent_id" OtherKey="id" Type="task_statuses" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tasks" Member="tasks">
    <Type Name="task">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="details" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="notifier_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="assignee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="clerk_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="task_task" Member="tasks" ThisKey="id" OtherKey="parent_id" Type="task" />
      <Association Name="task_tasks_call" Member="tasks_calls" ThisKey="id" OtherKey="task_id" Type="tasks_call" />
      <Association Name="person_task" Member="person" ThisKey="assignee_id" OtherKey="id" Type="person" IsForeignKey="true" />
      <Association Name="task_category_task" Member="task_category" ThisKey="category_id" OtherKey="id" Type="task_category" IsForeignKey="true" />
      <Association Name="person_task1" Member="person1" ThisKey="clerk_id" OtherKey="id" Type="person" IsForeignKey="true" />
      <Association Name="task_task" Member="task1" ThisKey="parent_id" OtherKey="id" Type="task" IsForeignKey="true" />
      <Association Name="task_statuse_task" Member="task_statuses" ThisKey="status_id" OtherKey="id" Type="task_statuses" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tasks_calls" Member="tasks_calls">
    <Type Name="tasks_call">
      <Column Name="call_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="task_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="call_tasks_call" Member="call" ThisKey="call_id" OtherKey="id" Type="call" IsForeignKey="true" />
      <Association Name="task_tasks_call" Member="task" ThisKey="task_id" OtherKey="id" Type="task" IsForeignKey="true" />
    </Type>
  </Table>
</Database>