#pragma checksum "..\..\..\..\NewFolder1\StandBy.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "1D8875EC4C33624B4F310A4035F1C06F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SIP_Agent {
    
    
    /// <summary>
    /// standby
    /// </summary>
    public partial class standby : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 4 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal SIP_Agent.standby standByWindow;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sNameLabel;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sNameBox;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sCompanyLabel;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sCompanyBox;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sPhoneLabel;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sPhoneBox;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sMailLabel;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sMailBox;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sDataLabel;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox sDataBox;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\NewFolder1\StandBy.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_sSaveData;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SIP Agent;component/newfolder1/standby.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\NewFolder1\StandBy.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.standByWindow = ((SIP_Agent.standby)(target));
            return;
            case 2:
            this.sNameLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.sNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.sCompanyLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.sCompanyBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.sPhoneLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.sPhoneBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.sMailLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.sMailBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.sDataLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.sDataBox = ((System.Windows.Controls.RichTextBox)(target));
            return;
            case 12:
            this.btn_sSaveData = ((System.Windows.Controls.Button)(target));
            
            #line 20 "..\..\..\..\NewFolder1\StandBy.xaml"
            this.btn_sSaveData.Click += new System.Windows.RoutedEventHandler(this.btn_sSaveData_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

