#pragma checksum "..\..\..\..\Menu\UserStandby.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "3779EFAC4E66EBCB1388AC7EE4A8A402"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SIP_Agent {
    
    
    /// <summary>
    /// UserStandby
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
    public partial class UserStandby : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sNameLabel;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sNameBox;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sCompanyLabel;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sCompanyBox;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sPhoneLabel;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sPhoneBox;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sMailLabel;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sMailBox;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label sDataLabel;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox sDataBox;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_sSaveData;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\Menu\UserStandby.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_UserMain;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SIP Agent;component/menu/userstandby.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Menu\UserStandby.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.sNameLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.sNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.sCompanyLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.sCompanyBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.sPhoneLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.sPhoneBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.sMailLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.sMailBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.sDataLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.sDataBox = ((System.Windows.Controls.RichTextBox)(target));
            return;
            case 11:
            this.btn_sSaveData = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\Menu\UserStandby.xaml"
            this.btn_sSaveData.Click += new System.Windows.RoutedEventHandler(this.btn_sSaveData_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btn_UserMain = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\Menu\UserStandby.xaml"
            this.btn_UserMain.Click += new System.Windows.RoutedEventHandler(this.btn_UserMain_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

